project_id = "gylxzoogrqqeqihqknkm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-leads]
verify_jwt = false

[functions.generate-leads-google]
verify_jwt = false

[functions.generate-ctas]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-whatsapp-evolution]
verify_jwt = false

[functions.webhook-whatsapp]
verify_jwt = false

[functions.webhook-whatsapp-evolution]
verify_jwt = false

[functions.webhook-sms]
verify_jwt = false

[functions.webhook-email]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.webhook-telegram]
verify_jwt = false

[functions.webhook-meta-leads]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.generate-leads-interest]
verify_jwt = false

[functions.generate-leads-interest-demo]
verify_jwt = false

[functions.generate-leads-web]
verify_jwt = false

[functions.run-automation]
verify_jwt = false

[functions.automation-scheduler]
verify_jwt = false
