project_id = "gylxzoogrqqeqihqknkm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-leads]
verify_jwt = false

[functions.generate-ctas]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
